Task2: transform regex to dfa and graph to nfa
homka122/formal-lang-course pull request #2
Opened 2024-09-12 07:10 UTC by homka122

- Add `regex_to_dfa` function to transform `regex` string to Deterministic Finite Automata
- Add `graph_to_nfa` function to transform `MultiDiGraph` graph to Non-Deterministic Finite Automata
- Enable autotests for `task2`

2024-09-17 13:29 UTC, vadyushkins requested changes

2024-09-17 13:29 UTC, vivalerievich commented on project/task1/main.py
> +    pydot_graph.write(path)
Этого не должно быть в этом PR

2024-09-17 13:29 UTC, vivalerievich commented on project/task2/main.py
> +    [nfa.add_final_state(State(node)) for node in final_states]
Зачем тут так написано? Вы уверены что Python однажды не оптимизирует и не выкинет эти строки? Даже если уверены, это плохая идея так писать как минимум потому что не читается

2024-09-17 13:29 UTC, vivalerievich commented on tests/test_task1.py
> +
Это что вообще? Где тесты на задачу номер два?
И тестов сразу добавьте достаточно. Крайние случаи учтите. Посмотрите параметризацию в pytest. Посмотрите как pytest создаем временные директории и файлы.

2024-09-24 14:47 UTC, vadyushkins commented on tests/test_task1.py
> +
Ладно, тесты можете не добавлять

2024-09-24 14:48 UTC, vadyushkins commented on project/task1/main.py
> +    pydot_graph.write(path)
Тут напишите фикс, вмержите его в main и в task2

2024-09-25 17:48 UTC, homka122 commented
Все исправил, подправил, теперь в ПР только изменения для task2 🙂

2024-10-18 07:29 UTC, vadyushkins approved these changes

2025-09-07 18:37 UTC, closed without merging